# Generated by Django 4.1.3 on 2022-11-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmi', '0002_familiar_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='nombre_ape',
            new_name='nombre',
        ),
    ]
