# Generated by Django 4.1.3 on 2022-11-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmi', '0003_rename_nombre_ape_familiar_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='tipo_de_pariente',
        ),
    ]
